# Generated by Django 4.0.5 on 2022-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4intern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='typee',
            field=models.IntegerField(choices=[(1, 'Patient'), (2, 'Doctor')], null=True),
        ),
    ]
