# Generated by Django 4.0.5 on 2022-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4intern', '0002_userdata_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='typee',
            field=models.CharField(default='Patient', max_length=20),
        ),
    ]
