# Generated by Django 4.0.2 on 2022-06-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4intern', '0003_alter_userdata_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
